import matplotlib.pyplot as plt
import pandas as pd

delta_1 = pd.read_csv('Delta_save_SARSA.csv')
delta_2 = pd.read_csv('Delta_save_QLearning.csv')
delta_3 = pd.read_csv('Delta_save_Adagrad_good.csv')
delta_4 = pd.read_csv('Delta_save_ER.csv')
# print(delta_1['Delta_save'])
delta_1['Delta_save'] = delta_1['Delta_save'].ewm(span=2000, adjust=False).mean()
delta_2['Delta_save'] = delta_2['Delta_save'].ewm(span=2000, adjust=False).mean()
delta_3['Delta_save'] = delta_3['Delta_save'].ewm(span=2000, adjust=False).mean()
delta_4['Delta_save'] = delta_4['Delta_save'].ewm(span=2000, adjust=False).mean()
plt.plot(delta_1['Delta_save'], label='SARSA')
plt.plot(delta_2['Delta_save'], label='Q Learning')
plt.plot(delta_3['Delta_save'], label='SARSA Adagrad')
plt.plot(delta_4['Delta_save'], label='Ex Replay')
plt.xlabel('Episodes')
plt.ylabel('Error')
plt.title('Average Loss')
plt.legend()
# plt.show()
plt.savefig('comp_new_report_delta.png')
plt.close()

N_moves_1 = pd.read_csv('N_moves_SARSA.csv')
N_moves_2 = pd.read_csv('N_moves_QLearning.csv')
N_moves_3 = pd.read_csv('N_moves_Adagrad_good.csv')
N_moves_4 = pd.read_csv('N_moves_ER.csv')
N_moves_1['N_moves'] = N_moves_1['N_moves'].ewm(span=2000, adjust=False).mean()
N_moves_2['N_moves'] = N_moves_2['N_moves'].ewm(span=2000, adjust=False).mean()
N_moves_3['N_moves'] = N_moves_3['N_moves'].ewm(span=2000, adjust=False).mean()
N_moves_4['N_moves'] = N_moves_4['N_moves'].ewm(span=2000, adjust=False).mean()
plt.plot(N_moves_1['N_moves'], label='SARSA')
plt.plot(N_moves_2['N_moves'], label='Q Learning')
plt.plot(N_moves_3['N_moves'], label='SARSA Adagrad')
plt.plot(N_moves_4['N_moves'], label='Ex Replay')
plt.xlabel('Episodes')
plt.ylabel('Number of Steps until "Done"')
plt.title('Average Number of Steps until "Done" per Episode')
# plt.show()
plt.savefig('comp_new_report_N_moves.png')
plt.close()

reward_1 = pd.read_csv('R_save_SARSA.csv')
reward_2 = pd.read_csv('R_save_QLearning.csv')
reward_3 = pd.read_csv('R_save_Adagrad_good.csv')
reward_4 = pd.read_csv('R_save_ER.csv')
reward_1['R_save'] = reward_1['R_save'].ewm(span=2000, adjust=False).mean()
reward_2['R_save'] = reward_2['R_save'].ewm(span=2000, adjust=False).mean()
reward_3['R_save'] = reward_3['R_save'].ewm(span=2000, adjust=False).mean()
reward_4['R_save'] = reward_3['R_save'].ewm(span=2000, adjust=False).mean()
plt.plot(reward_1['R_save'], label='SARSA')
plt.plot(reward_2['R_save'], label='Q Learning')
plt.plot(reward_3['R_save'], label='SARSA Adagrad')
plt.plot(reward_4['R_save'], label='Ex Replay')
plt.xlabel('Episodes')
plt.ylabel('Reward')
plt.title('Average Rewards per Episode')
plt.legend()
# plt.show()
plt.savefig('comp_new_report_reward.png')
plt.close()